### PR TITLE
Login register requests

### PR DESCRIPTION
**Pull request by hmpace**
Added login and registration pages. Also made a central request queue for volley. I messed up a rebase a few days ago, which is why there are some weird commits. Oh well! :sparkling_heart:

### CODE REVIEW

**Review by taangle — CHANGES_REQUESTED** [review]
* Something should indicate that the user is signed in, like maybe making the sign in button disappear.
* When I create an account in the app, I can sign in there. But I can't sign in through the website - it says I have an invalid email or password.
* There are some issues with the keyboard's enter button. It doesn't always act consistently on the sign-in and sign-up pages, and sometimes it focuses in on a button instead of a text field.

**Comment by taangle** [comment]
@hmpace sometimes, the first time I load up the app and try to log in, it just gives an error saying it can't reach the server. Then when I try with a different account it works, and the original account starts working too.

**Comment by hmpace** [comment]
> * Something should indicate that the user is signed in, like maybe making the sign in button disappear.

This is now implemented.
> * When I create an account in the app, I can sign in there. But I can't sign in through the website - it says I have an invalid email or password.
>* sometimes, the first time I load up the app and try to log in, it just gives an error saying it can't reach the server. Then when I try with a different account it works, and the original account starts working too.

These are both because I'm using a test server right now. It goes to sleep when inactive, and takes a little bit to spin up a dyno, causing the second issue. 
We can wait until my changes are on the production server before merging.

**Comment by taangle** [comment]
@hmpace sometimes the sign in button is still visible over the Upcoming Events. I think it specifically happens when you navigate back to the home page from an event page (and when Upcoming Events are expanded, of course).

**Comment by hmpace** [comment]
All of the above issues should now be fixed, with the exception of

> There are some issues with the keyboard's enter button. It doesn't always act consistently on the sign-in and sign-up pages, and sometimes it focuses in on a button instead of a text field.

,which I believe is a non-issue. It only occurs when using a physical keyboard, not when using the on-screen keyboard.

**Comment by taangle** [comment]
The sign-in button visibility issue is still there on my end.

**Comment by hmpace** [comment]
Yup, sorry about that. It should be good now.

**Pull request merged**
